version = 0.1

[default.deploy.parameters]
stack_name = "mnemospark-staging"
resolve_s3 = true
s3_prefix = "mnemospark-staging"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = "StageName=staging"
image_repositories = []
