version = 0.1

[default.deploy.parameters]
stack_name = "mnemospark-prod"
resolve_s3 = true
s3_prefix = "mnemospark-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = "EnvName=prod LogLevel=WARN ReservedConcurrency=25 AlarmEmail=ops@example.com"
image_repositories = []
