AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Object storage management REST API (Lambda + API Gateway). Upload/list/download/delete with client-held encryption; KEK in Secrets Manager.

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name

Resources:
  ObjectStorageManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: object-storage-management-api
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
          Description: Usage plan for object storage management API
          Throttle:
            RateLimit: 10
            BurstLimit: 20
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ObjectStorageManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: .
      MemorySize: 256
      Timeout: 60
      Events:
        PostStorage:
          Type: Api
          Properties:
            RestApiId: !Ref ObjectStorageManagementApi
            Path: /storage
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:CreateBucket
                - s3:HeadBucket
                - s3:PutObject
                - s3:GetObject
                - s3:HeadObject
                - s3:DeleteObject
                - s3:ListBucket
                - s3:DeleteBucket
              Resource:
                - !Sub "arn:aws:s3:::mnemospark-*"
                - !Sub "arn:aws:s3:::mnemospark-*/*"
            - Effect: Allow
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mnemospark/wallet/*"

Outputs:
  ApiUrl:
    Description: REST API endpoint URL (POST /storage with JSON body)
    Value: !Sub "https://${ObjectStorageManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/storage"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ObjectStorageManagementFunction.Arn
